import { useCallback } from 'react';
import type { ApiStaffBooking, ApiStaffDashboard, ApiStaffProductJob, ApiStaffTracker } from '../lib/api';

export type StaffData = {
  bookings: ApiStaffBooking[];
  trackers: ApiStaffTracker[];
  productJobs: ApiStaffProductJob[];
  dashboard: ApiStaffDashboard | null;
  loading: boolean;
  error: string | null;
  reload: () => void;
};

const demoBookings: ApiStaffBooking[] = [
  {
    id: 'BK-DEMO-1',
    customer: 'Minh Anh',
    phone: '0912345678',
    email: 'minhanh@demo.vn',
    workshop: 'Nặn gốm cơ bản',
    product: 'Ly men rêu',
    date: '05/06/2026',
    time: '19:00',
    people: 2,
    price: '980.000đ',
    status: 'confirmed',
    payment: 'paid',
    staff: 'Chị Linh',
    note: 'Quận 1 - khách muốn tông men trầm, cần gửi ảnh tiến độ.',
    checkin_status: 'checked_in',
    tracking_code: 'THO-DEMO-001',
    workshop_id: 1,
    chatbot_note: 'Khách thích trải nghiệm nhẹ nhàng, đi cùng bạn thân.',
    chatbot_style: 'Mộc, men rêu, ít họa tiết',
    chatbot_experience: 'first_timer',
    chatbot_purpose: 'Quà sinh nhật',
    chatbot_custom_request: 'Chụp vài ảnh quá trình để gửi lại sau workshop.',
  },
  {
    id: 'BK-DEMO-2',
    customer: 'Linh Nguyễn',
    phone: '0908123456',
    email: 'linhnguyen@demo.vn',
    workshop: 'Workshop cặp đôi',
    product: 'Bình celadon',
    date: '07/06/2026',
    time: '18:30',
    people: 2,
    price: '1.180.000đ',
    status: 'completed',
    payment: 'paid',
    staff: 'Anh Quân',
    note: 'Quận 3 - nhận tại studio.',
    checkin_status: 'checked_in',
    tracking_code: 'THO-DEMO-002',
    workshop_id: 3,
    chatbot_note: 'Muốn làm một cặp đồ gốm để kỷ niệm.',
    chatbot_style: 'Celadon sáng, dáng tối giản',
    chatbot_experience: 'returning',
    chatbot_purpose: 'Kỷ niệm cặp đôi',
    chatbot_custom_request: null,
  },
  {
    id: 'BK-DEMO-3',
    customer: 'Quỳnh Chi',
    phone: '0987654321',
    email: 'quynhchi@demo.vn',
    workshop: 'Tô men thư giãn',
    product: 'DIY kit',
    date: '09/06/2026',
    time: '09:00',
    people: 1,
    price: '490.000đ',
    status: 'pending',
    payment: 'waiting',
    staff: 'Chị Hạnh',
    note: 'Bình Thạnh - cần gọi nhắc trước 1 ngày.',
    checkin_status: 'pending',
    tracking_code: 'THO-DEMO-003',
    workshop_id: 2,
    chatbot_note: 'Khách mới, thích hoạt động chậm và ít áp lực.',
    chatbot_style: 'Màu pastel, hoa nhỏ',
    chatbot_experience: 'first_timer',
    chatbot_purpose: 'Thư giãn cuối tuần',
    chatbot_custom_request: 'Có thể đổi sang ca chiều nếu còn slot.',
  },
  {
    id: 'BK-DEMO-4',
    customer: 'An Tran',
    phone: '0933001122',
    email: 'antran@demo.vn',
    workshop: 'Nan gom co ban',
    product: 'Chen men nau',
    date: '10/06/2026',
    time: '10:00',
    people: 3,
    price: '1.470.000d',
    status: 'confirmed',
    payment: 'paid',
    staff: 'Chi Linh',
    note: 'Thu Duc - nhom ban cong ty, can gui anh sau workshop.',
    checkin_status: 'checked_in',
    tracking_code: 'THO-DEMO-004',
    workshop_id: 1,
    chatbot_note: 'Nhom di lan dau, uu tien hoat dong de bat dau.',
    chatbot_style: 'Men nau, dang tron',
    chatbot_experience: 'first_timer',
    chatbot_purpose: 'Team bonding',
    chatbot_custom_request: 'Can video ngan de gui group noi bo.',
  },
  {
    id: 'BK-DEMO-5',
    customer: 'Bao Nguyen',
    phone: '0944556677',
    email: 'bao@demo.vn',
    workshop: 'Workshop cap doi',
    product: 'Cap ly men kem',
    date: '11/06/2026',
    time: '18:30',
    people: 2,
    price: '1.180.000d',
    status: 'pending',
    payment: 'waiting',
    staff: 'Anh Quan',
    note: 'Go Vap - khach hoi ma tracking khi check-in.',
    checkin_status: 'pending',
    tracking_code: 'THO-DEMO-005',
    workshop_id: 3,
    chatbot_note: 'Muon lam qua tang ky niem.',
    chatbot_style: 'Kem, it hoa tiet',
    chatbot_experience: 'returning',
    chatbot_purpose: 'Ky niem',
    chatbot_custom_request: null,
  },
  {
    id: 'BK-DEMO-6',
    customer: 'Ha Pham',
    phone: '0966123456',
    email: 'ha@demo.vn',
    workshop: 'To men thu gian',
    product: 'Dia trang tri',
    date: '12/06/2026',
    time: '14:00',
    people: 1,
    price: '490.000d',
    status: 'completed',
    payment: 'paid',
    staff: 'Chi Hanh',
    note: 'Quan 7 - gift sinh nhat, can anh thanh pham.',
    checkin_status: 'checked_in',
    tracking_code: 'THO-DEMO-006',
    workshop_id: 2,
    chatbot_note: 'Thich mau pastel va hoa nho.',
    chatbot_style: 'Pastel, hoa nho',
    chatbot_experience: 'first_timer',
    chatbot_purpose: 'Qua sinh nhat',
    chatbot_custom_request: 'Upload anh thanh pham truoc khi dong goi.',
  },
  {
    id: 'BK-DEMO-7',
    customer: 'Khoa Le',
    phone: '0977008899',
    email: 'khoa@demo.vn',
    workshop: 'Nan gom co ban',
    product: 'Binh mini',
    date: '13/06/2026',
    time: '09:00',
    people: 4,
    price: '1.960.000d',
    status: 'confirmed',
    payment: 'paid',
    staff: 'Chi Linh',
    note: 'Quan 1 - nhom gia dinh, uu tien check-in nhanh.',
    checkin_status: 'checked_in',
    tracking_code: 'THO-DEMO-007',
    workshop_id: 1,
    chatbot_note: 'Gia dinh co tre nho, can buoi hoc cham.',
    chatbot_style: 'Moc, men reu',
    chatbot_experience: 'first_timer',
    chatbot_purpose: 'Gia dinh',
    chatbot_custom_request: null,
  },
  {
    id: 'BK-DEMO-8',
    customer: 'Mai Vo',
    phone: '0909003344',
    email: 'mai@demo.vn',
    workshop: 'Workshop cap doi',
    product: 'Binh celadon',
    date: '14/06/2026',
    time: '16:00',
    people: 2,
    price: '1.180.000d',
    status: 'confirmed',
    payment: 'paid',
    staff: 'Anh Quan',
    note: 'Quan 3 - muon xem video workshop sau khi ve.',
    checkin_status: 'pending',
    tracking_code: 'THO-DEMO-008',
    workshop_id: 3,
    chatbot_note: 'Quan tam den video va anh qua trinh.',
    chatbot_style: 'Celadon, toi gian',
    chatbot_experience: 'returning',
    chatbot_purpose: 'Hen ho',
    chatbot_custom_request: 'Can tao tracking code khi check-in.',
  },
];

const demoTrackers: ApiStaffTracker[] = [
  {
    id: 'TR-DEMO-1',
    booking_id: 'BK-DEMO-1',
    customer: 'Minh Anh',
    product: 'Ly men rêu',
    workshop: 'Nặn gốm cơ bản',
    stage: 'glazing',
    qc: 'need_photo',
    updated_at: '04/06/2026 15:20',
    owner: 'Chị Linh',
    kiln: 'Lò A2',
    tracking_code: 'THO-DEMO-001',
  },
  {
    id: 'TR-DEMO-2',
    booking_id: 'BK-DEMO-2',
    customer: 'Linh Nguyễn',
    product: 'Bình celadon',
    workshop: 'Workshop cặp đôi',
    stage: 'ready',
    qc: 'normal',
    updated_at: '04/06/2026 10:45',
    owner: 'Anh Quân',
    kiln: 'Lò B1',
    tracking_code: 'THO-DEMO-002',
  },
  {
    id: 'TR-DEMO-3',
    booking_id: 'BK-DEMO-3',
    customer: 'Quỳnh Chi',
    product: 'DIY kit',
    workshop: 'Tô men thư giãn',
    stage: 'drying',
    qc: 'normal',
    updated_at: '03/06/2026 17:05',
    owner: 'Chị Hạnh',
    kiln: 'Kệ phơi C',
    tracking_code: 'THO-DEMO-003',
  },
  {
    id: 'TR-DEMO-4',
    booking_id: 'BK-DEMO-4',
    customer: 'An Tran',
    product: 'Chen men nau',
    workshop: 'Nan gom co ban',
    stage: 'bisque',
    qc: 'normal',
    updated_at: '10/06/2026 16:10',
    owner: 'Chi Linh',
    kiln: 'Lo A1',
    tracking_code: 'THO-DEMO-004',
  },
  {
    id: 'TR-DEMO-5',
    booking_id: 'BK-DEMO-5',
    customer: 'Bao Nguyen',
    product: 'Cap ly men kem',
    workshop: 'Workshop cap doi',
    stage: 'created',
    qc: 'need_photo',
    updated_at: '11/06/2026 19:30',
    owner: 'Anh Quan',
    kiln: 'Ke cho xu ly',
    tracking_code: 'THO-DEMO-005',
  },
  {
    id: 'TR-DEMO-6',
    booking_id: 'BK-DEMO-6',
    customer: 'Ha Pham',
    product: 'Dia trang tri',
    workshop: 'To men thu gian',
    stage: 'final',
    qc: 'normal',
    updated_at: '12/06/2026 17:45',
    owner: 'Chi Hanh',
    kiln: 'Lo B2',
    tracking_code: 'THO-DEMO-006',
  },
];

const demoProductJobs: ApiStaffProductJob[] = [
  {
    id: 'PJ-DEMO-1',
    booking_id: 'BK-DEMO-1',
    customer: 'Minh Anh',
    product: 'Ly men rêu',
    stage: 'glazing',
    status: 'photo_needed',
    image: '2 ảnh',
    owner: 'Chị Linh',
    due: '10/06/2026',
  },
  {
    id: 'PJ-DEMO-2',
    booking_id: 'BK-DEMO-2',
    customer: 'Linh Nguyễn',
    product: 'Bình celadon',
    stage: 'ready',
    status: 'ready',
    image: '4 ảnh',
    owner: 'Anh Quân',
    due: '09/06/2026',
  },
  {
    id: 'PJ-DEMO-3',
    booking_id: 'BK-DEMO-3',
    customer: 'Quỳnh Chi',
    product: 'DIY kit',
    stage: 'drying',
    status: 'in_progress',
    image: '0 ảnh',
    owner: 'Chị Hạnh',
    due: '12/06/2026',
  },
  {
    id: 'PJ-DEMO-4',
    booking_id: 'BK-DEMO-4',
    customer: 'An Tran',
    product: 'Chen men nau',
    stage: 'bisque',
    status: 'in_progress',
    image: '1 anh',
    owner: 'Chi Linh',
    due: '15/06/2026',
  },
  {
    id: 'PJ-DEMO-5',
    booking_id: 'BK-DEMO-5',
    customer: 'Bao Nguyen',
    product: 'Cap ly men kem',
    stage: 'created',
    status: 'photo_needed',
    image: '0 anh',
    owner: 'Anh Quan',
    due: '16/06/2026',
  },
  {
    id: 'PJ-DEMO-6',
    booking_id: 'BK-DEMO-6',
    customer: 'Ha Pham',
    product: 'Dia trang tri',
    stage: 'final',
    status: 'ready',
    image: '3 anh',
    owner: 'Chi Hanh',
    due: '14/06/2026',
  },
];

const demoDashboard: ApiStaffDashboard = {
  today: 2,
  week: 15,
  customers: 8,
  revenue_million: 8.2,
  pending_checkin: 3,
  checked_in: 5,
  trackers_need_update: 4,
  qc_issues: 1,
  confirmed: 4,
  paid: 6,
  cancelled: 0,
};

export function useStaffData(_enabled: boolean): StaffData {
  const reload = useCallback(() => undefined, []);

  return {
    bookings: demoBookings,
    trackers: demoTrackers,
    productJobs: demoProductJobs,
    dashboard: demoDashboard,
    loading: false,
    error: null,
    reload,
  };
}
